
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[357] =
    {   0,
        0,    0,   77,   76,   68,   63,   54,   49,   76,   58,
       67,   46,   47,   73,   53,   61,   52,   75,   57,   64,
       56,   59,   69,   65,   62,   51,   50,   66,   73,   73,
       48,   55,   60,   12,   76,   73,   73,   73,   69,   70,
        0,    0,   73,   75,   75,   74,   75,   75,   74,   74,
       74,   74,   74,   74,    0,    0,   14,   73,   73,   73,
       12,   12,    0,   73,   73,   73,   73,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   72,   75,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   73,   73,   73,   73,   73,   13,

        0,   73,   73,   73,   73,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   31,    0,    0,   34,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       10,   73,   73,    8,   73,   73,   13,   13,   13,    0,
       73,   73,   73,   73,    0,    0,   19,    0,    0,   22,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   11,    6,   73,    9,    0,   73,    4,   73,   73,

        0,    0,    0,    0,   21,    0,   23,   25,    0,    0,
        0,    0,    0,   32,    0,    0,    0,    0,    0,   38,
        0,    0,    0,    0,    0,   45,   74,   74,   74,   74,
       74,   74,   71,   74,   74,   74,   74,    7,    0,    3,
        2,   73,    0,    0,    0,    0,   24,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   39,   41,    0,
       42,    0,    0,   74,   74,   74,   74,   74,   74,   74,
       74,    5,    1,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   33,   35,    0,    0,    0,   15,   40,    0,
        0,   74,   74,   74,   74,   74,   74,   74,   16,    0,

        0,    0,    0,    0,    0,   30,   29,    0,    0,    0,
        0,   74,   74,   74,   74,   74,    0,    0,   20,    0,
        0,    0,   36,   37,   44,   43,   74,   74,   74,   74,
       18,   17,    0,    0,   26,   74,   74,   74,   74,   28,
       27,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   37,   38,   39,   40,   41,   42,
       37,   43,   44,   45,   46,   47,   37,   48,   49,   37,
       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,

       60,   61,   62,   63,   64,   65,   37,   66,   67,   68,
       69,   70,   71,   72,   73,   74,   75,   76,   77,   78,
       37,   37,   79,   80,   81,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[82] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    1,    3,    4,    5,    4,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        3,    1,    1,    3,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[365] =
    {   0,
        0,   80,  841,  842,  842,  816,  815,   74,  820,  842,
      842,  842,  842,   66,   72,  842,   74,   84,  819,   74,
      842,  842,  842,  842,  812,  842,  842,  780,   87,   89,
      842,  810,  842,  782,  773,   91,   93,   95,  842,  842,
      116,    0,   99,  103,  111,  113,  116,  118,  128,  146,
      177,  149,  180,  184,  807,  775,  842,  139,  123,  187,
      778,  140,  768,  160,  189,  191,  195,  165,  771,  770,
      761,   73,  162,  763,  754,  753,  749,  764,  759,  166,
      762,   30,  799,  842,  218,  224,  239,  244,  249,  252,
      255,  258,  262,  265,  200,  231,  272,  278,  283,  150,

      755,  286,  288,  290,  292,  742,  755,  754,  739,  745,
      738,  737,  752,  246,  751,  734,  842,  741,  730,  739,
      728,  745,  740,  727,  726,  126,  731,  722,  711,  297,
      301,  304,  310,  321,  318,  336,  343,  346,  349,  352,
      308,  316,  328,  356,  360,  364,  716,  382,  262,  702,
      372,  375,  377,  379,  695,  329,  842,  704,  697,  842,
      693,  695,  165,  701,  686,  682,  697,  688,  695,  690,
      678,  684,  683,  674,  683,  673,  684,  656,  671,  669,
      385,  389,  394,  398,  403,  410,  406,  424,  432,  438,
      443,  382,  392,  429,  446,  658,  448,  450,  452,  455,

      669,  639,  627,  633,  842,  627,  842,  842,  637,  623,
      600,  604,  615,  842,  606,  602,  589,  593,  594,  842,
      585,  573,  575,  571,  572,  562,  457,  462,  465,  468,
      473,  478,  483,  486,  497,  500,  504,  511,  563,  513,
      515,  517,  527,  536,  523,  527,  842,  503,  500,  490,
      491,  504,  489,  486,  496,  469,  500,  842,  842,  433,
      842,  453,  443,  519,  522,  528,  531,  537,  540,  550,
      553,  842,  525,  436,  428,  398,  386,  428,  367,  363,
      355,  356,  842,  842,  342,  332,  379,  842,  842,  316,
      307,  561,  569,  572,  575,  580,  586,  589,  842,  293,

      280,  271,  234,  235,  220,  842,  842,  212,  191,  193,
      171,  592,  596,  599,  602,  607,  156,  154,  842,  152,
      102,  103,  842,  842,  842,  842,  618,  623,  626,  630,
      842,  842,   64,   63,  842,  633,  639,  649,  657,  842,
      842,  660,  663,  666,  669,  672,  686,  689,  695,  698,
      701,  704,  717,  721,  724,  842,  766,  769,  772,  776,
      781,  116,  786,  791
    } ;

static const flex_int16_t yy_def[365] =
    {   0,
      356,    1,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  357,  357,  356,  357,  358,  359,  356,
      356,  356,  356,  356,  356,  356,  356,  360,  357,  357,
      356,  356,  356,  361,  356,  357,  357,  357,  356,  356,
      356,  362,  357,  358,  359,  358,  359,  359,  358,  358,
      358,  358,  358,  358,  356,  360,  356,  357,  357,  357,
      361,  361,  356,  357,  357,  357,  357,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  362,  356,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  357,  357,  357,  357,  357,  363,

      356,  357,  357,  357,  357,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      357,  357,  357,  357,  357,  357,  363,  363,  363,  356,
      357,  357,  357,  357,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  357,  357,  357,  357,  356,  357,  357,  357,  357,

      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  357,  356,  357,
      357,  357,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  364,  356,  356,  356,
      356,  356,  356,  358,  358,  358,  358,  358,  358,  358,
      358,  356,  357,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  364,  356,  356,  356,
      356,  358,  358,  358,  358,  358,  358,  358,  356,  356,

      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  358,  358,  358,  358,  358,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  358,  358,  358,  358,
      356,  356,  356,  356,  356,  358,  358,  358,  358,  356,
      356,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,    0,  356,  356,  356,  356,
      356,  356,  356,  356
    } ;

static const flex_int16_t yy_nxt[924] =
    {   0,
        4,    4,    5,    4,    6,    7,    4,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   14,
       20,   21,   22,   23,   24,   25,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   26,
       14,   27,    4,   14,   28,   14,   14,   14,   14,   29,
       14,   14,   14,   30,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   31,   32,
       33,   34,   40,   44,   45,   41,   35,   40,   40,   44,
       45,   44,   45,  128,   55,   39,   40,   39,  129,   40,

       40,   47,   45,   48,   44,   45,   44,   45,   44,   45,
       44,   45,   44,   45,   49,   50,   44,   45,   83,   51,
       47,   45,   48,   52,  341,   53,   40,   54,   47,   84,
       44,   45,   48,   47,   45,   47,   45,  340,   36,   37,
       44,   45,  100,   38,  112,   44,   45,   48,  113,   60,
       64,  148,   58,  148,   59,   60,   44,   45,   58,   85,
       65,  335,   67,   44,   45,   48,   44,   45,   48,  334,
       66,   68,   69,   70,   71,   72,   73,   44,   45,   74,
       75,   96,  176,   76,   77,   78,  177,   79,   80,   89,
       62,   81,   82,   86,   44,   45,   48,   44,   45,   48,

      149,   44,   45,   48,   44,   45,   44,   45,   44,   45,
       87,   95,   44,   45,   90,   92,   88,   44,   45,   93,
      102,  106,   91,  107,  208,  114,  333,  115,  123,   94,
      116,  332,  108,  331,  124,   44,   45,   48,  209,  125,
      126,   44,   45,   48,  326,   97,   98,  103,   44,   45,
      130,  325,  105,  324,   99,  131,   44,   45,   48,  141,
      104,   44,   45,   48,  100,  132,   44,   45,   48,   44,
       45,   48,   44,   45,   48,   44,   45,   48,  133,   44,
       45,   48,   44,   45,   48,  323,  137,  138,  134,   44,
       45,  322,  136,  135,  142,   44,   45,  140,  321,  139,

       44,   45,  320,   44,   45,   44,   45,   44,   45,   44,
       45,  163,  149,  164,   44,   45,   48,  165,   44,   45,
       48,   44,   45,   48,  181,   44,   45,   44,   45,   48,
      319,  143,  182,   44,   45,   44,   45,   48,   44,   45,
       48,  145,  146,  318,  183,   44,   45,  152,  144,  151,
      184,  142,  185,   44,   45,   48,  317,  154,  153,  186,
       44,   45,   48,   44,   45,   48,   44,   45,   48,   44,
       45,   48,  188,   44,   45,  187,  192,   44,   45,  311,
      190,   44,   45,  148,  191,  148,  189,  310,  193,   44,
       45,  288,   44,   45,   44,   45,   44,   45,  202,   44,

       45,  203,   44,   45,   48,  309,   44,   45,   48,   44,
       45,   44,   45,   48,  308,   44,   45,   48,  307,  194,
       44,   45,   48,   44,   45,   48,  306,   44,   45,   48,
      227,  305,  149,  228,  195,  198,  229,  232,  304,  197,
      230,   44,   45,   48,  303,  231,   44,   45,  199,   44,
       45,   48,  302,  200,  233,   44,   45,   48,  301,  234,
       44,   45,   48,   44,   45,   44,   45,   44,   45,   44,
       45,  235,   44,   45,   44,   45,   48,  236,  237,   44,
       45,   48,   44,   45,   48,   44,   45,   48,  300,  238,
       44,   45,   48,  265,  264,   44,   45,   48,  299,  233,

       44,   45,   48,   44,   45,   48,  291,  240,  290,  266,
      289,  267,  288,  242,   44,   45,   48,   44,   45,   48,
      268,   44,   45,   48,  286,  241,  269,  270,   44,   45,
       44,   45,   44,   45,   44,   45,   44,   45,   48,   44,
       45,   48,   44,   45,  233,   44,   45,   48,   44,   45,
       48,  271,  285,  284,   44,   45,   48,   44,   45,   48,
      283,  282,  294,  233,  295,  281,  280,   44,   45,   48,
       44,   45,   48,  279,  278,  292,  273,  297,   44,   45,
       48,  293,  277,  276,  298,  296,   44,   45,   48,   44,
       45,   48,   44,   45,   48,  275,  313,   44,   45,   48,

      274,  312,  314,   44,   45,   48,   44,   45,   48,   44,
       45,   48,  315,   44,   45,   48,   44,   45,   48,   44,
       45,   48,  272,  233,   44,   45,   48,  263,  316,  262,
      261,  327,  233,  328,  329,   44,   45,   48,  260,  330,
       44,   45,   48,   44,   45,   48,  259,   44,   45,   48,
       44,   45,   48,  338,  258,  233,   44,   45,   48,  257,
      337,  339,  256,  255,  342,  254,   44,   45,   48,  253,
      252,  336,  251,  250,   44,   45,   48,   44,   45,   48,
       44,   45,   48,   44,   45,   48,   44,   45,   48,   44,
       45,   48,  343,  344,  233,  249,  248,  233,  247,  348,

      246,  245,  345,   44,   45,   48,   44,   45,   48,  346,
      244,  347,   44,   45,   48,   44,   45,   48,   44,   45,
       48,   44,   45,   48,  243,  239,  349,  226,  352,  225,
      224,  350,  353,  351,   44,   45,   48,  233,   44,   45,
       48,   44,   45,   48,  223,  222,  221,  220,  219,  218,
      217,  216,  355,  215,  354,  214,  213,  212,  211,  210,
      207,  206,  205,  204,  201,  196,  149,  233,   43,   43,
       43,   46,   46,   46,   48,   48,   56,   56,   56,   56,
       56,   61,  180,   61,   61,   61,  147,  179,  147,  147,
      147,  287,  287,  287,  287,  287,  178,  175,  174,  173,

      172,  171,  170,  169,  168,  167,  166,  162,  161,  160,
      159,  158,  157,  156,  155,  150,   42,  127,  122,  121,
      120,  119,  118,  117,  111,  110,  109,  101,   62,   57,
       39,   63,   62,   39,   57,   39,   47,   42,   39,   39,
      356,    3,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,

      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356
    } ;

static const flex_int16_t yy_chk[924] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    8,   14,   14,    8,    2,    8,    8,   15,
       15,   17,   17,   82,   20,   15,    8,   20,   82,    8,

        8,   18,   18,   18,   29,   29,   30,   30,   36,   36,
       37,   37,   38,   38,   18,   18,   43,   43,  362,   18,
       44,   44,   44,   18,  334,   18,    8,   18,   45,   45,
       46,   46,   46,   47,   47,   48,   48,  333,    2,    2,
       59,   59,   62,    2,   72,   49,   49,   49,   72,   30,
       36,  100,   29,  100,   29,   38,   58,   58,   37,   49,
       37,  322,   38,   50,   50,   50,   52,   52,   52,  321,
       37,   41,   41,   41,   41,   41,   41,   64,   64,   41,
       41,   59,  126,   41,   41,   41,  126,   41,   41,   52,
       62,   41,   41,   50,   51,   51,   51,   53,   53,   53,

      100,   54,   54,   54,   60,   60,   65,   65,   66,   66,
       51,   58,   67,   67,   53,   54,   51,   95,   95,   54,
       64,   68,   53,   68,  163,   73,  320,   73,   80,   54,
       73,  318,   68,  317,   80,   85,   85,   85,  163,   80,
       80,   86,   86,   86,  311,   60,   60,   65,   96,   96,
       85,  310,   67,  309,   60,   85,   87,   87,   87,   95,
       66,   88,   88,   88,  149,   86,   89,   89,   89,   90,
       90,   90,   91,   91,   91,   92,   92,   92,   87,   93,
       93,   93,   94,   94,   94,  308,   91,   92,   88,   97,
       97,  305,   90,   89,   96,   98,   98,   94,  304,   93,

       99,   99,  303,  102,  102,  103,  103,  104,  104,  105,
      105,  114,  149,  114,  130,  130,  130,  114,  131,  131,
      131,  132,  132,  132,  130,  141,  141,  133,  133,  133,
      302,   97,  131,  142,  142,  135,  135,  135,  134,  134,
      134,   99,   99,  301,  132,  143,  143,  103,   98,  102,
      133,  103,  134,  136,  136,  136,  300,  105,  104,  135,
      137,  137,  137,  138,  138,  138,  139,  139,  139,  140,
      140,  140,  137,  144,  144,  136,  142,  145,  145,  291,
      139,  146,  146,  148,  140,  148,  138,  290,  143,  151,
      151,  287,  152,  152,  153,  153,  154,  154,  156,  192,

      192,  156,  181,  181,  181,  286,  182,  182,  182,  193,
      193,  183,  183,  183,  285,  184,  184,  184,  282,  145,
      185,  185,  185,  187,  187,  187,  281,  186,  186,  186,
      181,  280,  148,  182,  146,  152,  183,  186,  279,  151,
      184,  188,  188,  188,  278,  185,  194,  194,  153,  189,
      189,  189,  277,  154,  187,  190,  190,  190,  276,  188,
      191,  191,  191,  195,  195,  197,  197,  198,  198,  199,
      199,  189,  200,  200,  227,  227,  227,  190,  191,  228,
      228,  228,  229,  229,  229,  230,  230,  230,  275,  194,
      231,  231,  231,  228,  227,  232,  232,  232,  274,  230,

      233,  233,  233,  234,  234,  234,  263,  197,  262,  229,
      260,  231,  257,  200,  235,  235,  235,  236,  236,  236,
      232,  237,  237,  237,  256,  199,  234,  235,  238,  238,
      240,  240,  241,  241,  242,  242,  264,  264,  264,  265,
      265,  265,  273,  273,  236,  266,  266,  266,  267,  267,
      267,  237,  255,  254,  268,  268,  268,  269,  269,  269,
      253,  252,  267,  264,  268,  251,  250,  270,  270,  270,
      271,  271,  271,  249,  248,  265,  242,  270,  292,  292,
      292,  266,  246,  245,  271,  269,  293,  293,  293,  294,
      294,  294,  295,  295,  295,  244,  293,  296,  296,  296,

      243,  292,  294,  297,  297,  297,  298,  298,  298,  312,
      312,  312,  295,  313,  313,  313,  314,  314,  314,  315,
      315,  315,  239,  296,  316,  316,  316,  226,  297,  225,
      224,  312,  298,  313,  314,  327,  327,  327,  223,  315,
      328,  328,  328,  329,  329,  329,  222,  330,  330,  330,
      336,  336,  336,  329,  221,  316,  337,  337,  337,  219,
      328,  330,  218,  217,  336,  216,  338,  338,  338,  215,
      213,  327,  212,  211,  339,  339,  339,  342,  342,  342,
      343,  343,  343,  344,  344,  344,  345,  345,  345,  346,
      346,  346,  337,  338,  339,  210,  209,  344,  206,  346,

      204,  203,  342,  347,  347,  347,  348,  348,  348,  343,
      202,  345,  349,  349,  349,  350,  350,  350,  351,  351,
      351,  352,  352,  352,  201,  196,  347,  180,  351,  179,
      178,  348,  352,  350,  353,  353,  353,  349,  354,  354,
      354,  355,  355,  355,  177,  176,  175,  174,  173,  172,
      171,  170,  354,  169,  353,  168,  167,  166,  165,  164,
      162,  161,  159,  158,  155,  150,  147,  355,  357,  357,
      357,  358,  358,  358,  359,  359,  360,  360,  360,  360,
      360,  361,  129,  361,  361,  361,  363,  128,  363,  363,
      363,  364,  364,  364,  364,  364,  127,  125,  124,  123,

      122,  121,  120,  119,  118,  116,  115,  113,  112,  111,
      110,  109,  108,  107,  106,  101,   83,   81,   79,   78,
       77,   76,   75,   74,   71,   70,   69,   63,   61,   56,
       55,   35,   34,   32,   28,   25,   19,    9,    7,    6,
        3,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,

      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mf.lex"
#line 2 "mf.lex"
#include "mf.tab.h"
#line 769 "lex.yy.c"
#line 770 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 8 "mf.lex"


#line 993 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 357 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 842 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 10 "mf.lex"
{return INCLUDE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 11 "mf.lex"
{return EXPORT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 13 "mf.lex"
{return DEFINE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 14 "mf.lex"
{return ENDEF;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 16 "mf.lex"
{return DEFINELINE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 18 "mf.lex"
{return IFDEF;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 19 "mf.lex"
{return IFNDEF;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 20 "mf.lex"
{return IFEQ;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 21 "mf.lex"
{return IFNEQ;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 22 "mf.lex"
{return ELSE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 23 "mf.lex"
{return ENDIF;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 26 "mf.lex"
{return COMMAND;}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 27 "mf.lex"
{return COMMAND;}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 29 "mf.lex"
{return SHELL_COMMAND;}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 30 "mf.lex"
{return SHELL_COMMAND;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 32 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 33 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 34 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 35 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 36 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 37 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 38 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 39 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 40 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 41 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 42 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 43 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 44 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 45 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 46 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 47 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 48 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 49 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 50 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 51 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 52 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 53 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 54 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 55 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 56 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 57 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 58 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 59 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 60 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 61 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 63 "mf.lex"
{ return '('; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 64 "mf.lex"
{ return ')'; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 65 "mf.lex"
{ return '{'; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 66 "mf.lex"
{ return '$'; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 67 "mf.lex"
{ return ']'; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 68 "mf.lex"
{ return '['; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 69 "mf.lex"
{ return '-'; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 70 "mf.lex"
{ return '+'; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 71 "mf.lex"
{ return '"'; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 72 "mf.lex"
{ return '|'; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 73 "mf.lex"
{ return ';'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 74 "mf.lex"
{ return '/'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 75 "mf.lex"
{ return '&'; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 76 "mf.lex"
{ return '<'; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 77 "mf.lex"
{ return '}'; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 78 "mf.lex"
{ return ','; }           
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 79 "mf.lex"
{ return '?'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 80 "mf.lex"
{ return '!'; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 81 "mf.lex"
{ return ':'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 82 "mf.lex"
{ return '>'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 83 "mf.lex"
{ return '`'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 84 "mf.lex"
{ return '\''; }
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 86 "mf.lex"
{ return EOL;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 89 "mf.lex"
{return VAR_DEF;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 90 "mf.lex"
{return VAR_AUT;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 92 "mf.lex"
{ return SPECIAL; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 94 "mf.lex"
{return TEMPLATE;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 96 "mf.lex"
{yylval.str = strdup(yytext); return NAME;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 97 "mf.lex"
{yylval.str = strdup(yytext); return FILE_NAME;}  
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 98 "mf.lex"
{yylval.str = strdup(yytext); return PATH;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 99 "mf.lex"
ECHO;
	YY_BREAK
#line 1435 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 357 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 357 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 356);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 99 "mf.lex"



int yywrap()
{
	return 1;
}

