
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 77
#define YY_END_OF_BUFFER 78
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[359] =
    {   0,
        0,    0,   78,   77,   70,   65,   56,   12,   51,   13,
       60,   69,   48,   49,   74,   55,   63,   54,   76,   59,
       66,   58,   61,   71,   67,   64,   53,   52,   68,   74,
       74,   50,   57,   62,   14,   12,   74,   74,   74,   71,
       12,   72,    0,    0,   74,   76,   76,   75,   76,   76,
       75,   75,   75,   75,   75,   75,    0,    0,   16,   74,
       74,   74,   14,   14,   12,   74,   74,   74,   74,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   13,   76,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   74,   74,   74,   74,

       74,   15,   12,   74,   74,   74,   74,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   33,    0,
        0,   36,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   10,   74,   74,    8,   74,   74,   15,   15,
       15,   12,   74,   74,   74,   74,    0,    0,   21,    0,
        0,   24,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   11,    6,   74,    9,   12,   74,    4,

       74,   74,    0,    0,    0,    0,   23,    0,   25,   27,
        0,    0,    0,    0,    0,   34,    0,    0,    0,    0,
        0,   40,    0,    0,    0,    0,    0,   47,   75,   75,
       75,   75,   75,   75,   73,   75,   75,   75,   75,    7,
       12,    3,    2,   74,    0,    0,    0,    0,   26,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   41,
       43,    0,   44,    0,    0,   75,   75,   75,   75,   75,
       75,   75,   75,    5,    1,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   35,   37,    0,    0,    0,   17,
       42,    0,    0,   75,   75,   75,   75,   75,   75,   75,

       18,    0,    0,    0,    0,    0,    0,   32,   31,    0,
        0,    0,    0,   75,   75,   75,   75,   75,    0,    0,
       22,    0,    0,    0,   38,   39,   46,   45,   75,   75,
       75,   75,   20,   19,    0,    0,   28,   75,   75,   75,
       75,   30,   29,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   37,   38,   39,   40,   41,   42,
       37,   43,   44,   45,   46,   47,   37,   48,   49,   37,
       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,

       60,   61,   62,   63,   64,   65,   37,   66,   67,   68,
       69,   70,   71,   72,   73,   74,   75,   76,   77,   78,
       37,   37,   79,   80,   81,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[82] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    1,    3,    4,    5,    4,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        3,    1,    1,    3,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[369] =
    {   0,
        0,   80,  876,  877,  877,  851,  850,    0,   74,    0,
      877,  877,  877,  877,   66,   72,  877,   74,   84,  855,
       74,  877,  877,  877,  877,  848,  877,  877,  816,   87,
       89,  877,  846,  877,  818,  809,   91,   93,   95,  877,
        0,  877,  116,    0,   99,  103,  111,  113,  116,  118,
      128,  146,  177,  149,  180,  184,  843,  811,  877,  139,
      123,  187,  814,  140,  804,  160,  189,  191,  195,  165,
      807,  806,  797,   73,  162,  799,  790,  789,  785,  800,
      795,  166,  798,   30,  261,  877,  218,  270,  224,  273,
      276,  279,  283,  287,  240,  290,  306,  308,  310,  312,

      314,  150,  792,  316,  318,  231,  320,  779,  792,  791,
      776,  782,  775,  774,  789,  277,  788,  771,  877,  778,
      767,  776,  765,  782,  777,  764,  763,  126,  768,  767,
      760,  328,  332,  335,  340,  343,  349,  369,  374,  377,
      380,  383,  200,  366,  387,  257,  389,  392,  780,  375,
      362,  766,  396,  401,  403,  405,  759,  184,  877,  768,
      761,  877,  757,  759,  165,  765,  750,  746,  753,  740,
      731,  723,  709,  715,  714,  705,  714,  704,  715,  700,
      715,  714,  410,  413,  416,  422,  425,  419,  432,  435,
      454,  458,  464,  442,  448,  451,  467,  704,  469,  471,

      473,  477,  715,  697,  692,  698,  877,  693,  877,  877,
      704,  690,  688,  692,  704,  877,  683,  681,  668,  672,
      674,  877,  656,  651,  652,  654,  652,  643,  483,  486,
      489,  495,  504,  512,  519,  522,  526,  530,  533,  492,
      638,  498,  501,  507,  609,  622,  618,  622,  877,  591,
      584,  573,  574,  589,  573,  550,  559,  559,  596,  877,
      877,  521,  877,  541,  516,  540,  546,  550,  554,  559,
      564,  570,  573,    0,  543,  513,  510,  495,  487,  518,
      461,  459,  427,  434,  877,  877,  420,  405,  444,  877,
      877,  374,  352,  576,  583,  588,  594,  602,  605,  608,

      877,  353,  326,  311,  288,  280,  250,  877,  877,  245,
      241,  193,  171,  611,  615,  618,  621,  624,  156,  154,
      877,  152,  102,  103,  877,  877,  877,  877,  637,  642,
      646,  649,  877,  877,   64,   63,  877,  652,  657,  667,
      670,  877,  877,  674,  677,  681,  684,  687,  700,  703,
      710,  713,  716,  719,  732,  736,  739,  877,  783,  788,
      791,  794,  797,  801,  806,  116,  811,  816
    } ;

static const flex_int16_t yy_def[369] =
    {   0,
      358,    1,  358,  358,  358,  358,  358,  359,  358,  360,
      358,  358,  358,  358,  361,  361,  358,  361,  362,  363,
      358,  358,  358,  358,  358,  358,  358,  358,  364,  361,
      361,  358,  358,  358,  365,  359,  361,  361,  361,  358,
      359,  358,  358,  366,  361,  362,  363,  362,  363,  363,
      362,  362,  362,  362,  362,  362,  358,  364,  358,  361,
      361,  361,  365,  365,  359,  361,  361,  361,  361,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  366,  358,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  361,  361,  361,  361,

      361,  367,  359,  361,  361,  361,  361,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  361,  361,  361,  361,  361,  361,  367,  367,
      367,  359,  361,  361,  361,  361,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  361,  361,  361,  361,  359,  361,  361,

      361,  361,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  361,
      359,  361,  361,  361,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  368,  358,
      358,  358,  358,  358,  358,  362,  362,  362,  362,  362,
      362,  362,  362,  359,  361,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  368,  358,
      358,  358,  358,  362,  362,  362,  362,  362,  362,  362,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  362,  362,  362,  362,  362,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  362,  362,
      362,  362,  358,  358,  358,  358,  358,  362,  362,  362,
      362,  358,  358,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,    0,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358
    } ;

static const flex_int16_t yy_nxt[959] =
    {   0,
        4,    4,    5,    4,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   15,
       21,   22,   23,   24,   25,   26,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   27,
       15,   28,    4,   15,   29,   15,   15,   15,   15,   30,
       15,   15,   15,   31,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   32,   33,
       34,   35,   42,   46,   47,   43,   36,   42,   42,   46,
       47,   46,   47,  130,   57,   40,   42,   40,  131,   42,

       42,   49,   47,   50,   46,   47,   46,   47,   46,   47,
       46,   47,   46,   47,   51,   52,   46,   47,   85,   53,
       49,   47,   50,   54,  343,   55,   42,   56,   49,   86,
       46,   47,   50,   49,   47,   49,   47,  342,   37,   38,
       46,   47,  102,   39,  114,   46,   47,   50,  115,   62,
       66,  150,   60,  150,   61,   62,   46,   47,   60,   87,
       67,  337,   69,   46,   47,   50,   46,   47,   50,  336,
       68,   70,   71,   72,   73,   74,   75,   46,   47,   76,
       77,   98,  178,   78,   79,   80,  179,   81,   82,   91,
       64,   83,   84,   88,   46,   47,   50,   46,   47,   50,

      151,   46,   47,   50,   46,   47,   46,   47,   46,   47,
       89,   97,   46,   47,   92,   94,   90,   46,   47,   95,
      104,  108,   93,  109,  210,  116,  335,  117,  125,   96,
      118,  334,  110,  333,  126,   46,   47,   50,  211,  127,
      128,   46,   47,   50,  328,   99,  100,  105,   46,   47,
      132,  327,  107,  204,  101,  133,  205,   46,   47,   50,
      106,   44,   44,  135,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   46,   47,   44,  141,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   46,   47,   50,
       46,   47,   50,   46,   47,   50,   46,   47,   50,  155,

       46,   47,   50,  326,   46,   47,   50,   46,   47,   50,
       44,  134,   44,   44,  139,   44,  140,  136,  325,  138,
      137,  324,  142,   46,   47,   46,   47,   46,   47,   46,
       47,   46,   47,   46,   47,   46,   47,   46,   47,   44,
       44,   44,  165,  323,  166,   46,   47,   50,  167,   46,
       47,   50,   46,   47,   50,  183,  322,   46,   47,   50,
       46,   47,   50,  184,  102,  143,   46,   47,   50,  145,
      321,  144,  147,  148,  187,  185,  150,  154,  150,  153,
      186,  144,  146,   46,   47,  156,   46,   47,   50,  320,
      188,   46,   47,   50,   46,   47,   50,   46,   47,   50,

       46,   47,   50,  190,   46,   47,   46,   47,  189,   46,
       47,  192,  151,   46,   47,  193,  319,  191,   46,   47,
       46,   47,   46,   47,  313,  151,  194,   46,   47,   50,
       46,   47,   50,   46,   47,   50,   46,   47,   50,   46,
       47,   50,   46,   47,   50,  312,  234,  195,  196,   46,
       47,   50,   46,   47,   50,  229,  290,  230,  231,   46,
       47,  200,  197,  199,  232,   46,   47,  233,   46,   47,
      236,   46,   47,   50,  201,   46,   47,   50,  311,  202,
      235,   46,   47,   50,   46,   47,   46,   47,   46,   47,
       46,   47,  310,  237,   46,   47,  309,  238,  308,  239,

       46,   47,   50,   46,   47,   50,   46,   47,   50,   46,
       47,  240,   46,   47,   50,   46,   47,  267,   46,   47,
      266,   46,   47,   50,   46,   47,  235,  307,  242,   46,
       47,   50,  306,  268,  305,  244,   46,   47,   50,   46,
       47,   50,  269,   46,   47,   50,  243,   46,   47,   50,
       46,   47,   50,  304,  270,  303,  272,   46,   47,   50,
       46,   47,  271,   46,   47,   50,  275,   46,   47,   50,
      302,   46,   47,   50,  235,  301,   46,   47,   50,  293,
      273,   46,   47,   50,  235,  296,  297,   46,   47,   50,
       46,   47,   50,   46,   47,   50,  292,  299,  291,  294,

       46,   47,   50,  295,  300,   46,   47,   50,  290,  298,
      315,   46,   47,   50,  288,  287,  314,  286,  316,   46,
       47,   50,   46,   47,   50,   46,   47,   50,   46,   47,
       50,  317,   46,   47,   50,   46,   47,   50,   46,   47,
       50,   46,   47,   50,  285,  235,  284,  318,  283,  282,
      329,  235,  330,  331,   46,   47,   50,  281,  332,   46,
       47,   50,  280,   46,   47,   50,   46,   47,   50,   46,
       47,   50,  235,  340,   46,   47,   50,  279,  278,  339,
      341,  277,  276,  344,   46,   47,   50,   46,   47,   50,
      338,   46,   47,   50,   46,   47,   50,  274,   46,   47,

       50,   46,   47,   50,   46,   47,   50,  235,  265,  264,
      345,  346,  235,  263,  350,  262,  347,   46,   47,   50,
       46,   47,   50,  348,  261,  260,  349,   46,   47,   50,
       46,   47,   50,   46,   47,   50,   46,   47,   50,  259,
      351,  258,  257,  354,  256,  352,  255,  355,  353,   46,
       47,   50,  235,   46,   47,   50,   46,   47,   50,  254,
      253,  252,  251,  250,  249,  248,  247,  357,  246,  356,
      245,  241,  228,  227,  226,  225,  224,  223,  222,  221,
      220,  219,  235,   41,  218,   41,   41,   41,   44,  217,
       44,   44,   44,   45,   45,   45,   48,   48,   48,   50,

       50,   58,   58,   58,   58,   58,   63,  216,   63,   63,
       63,  149,  215,  149,  149,  149,  289,  289,  289,  289,
      289,  214,  213,  212,  209,  208,  207,  206,  203,  198,
      151,  182,  181,  180,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  164,  163,  162,  161,  160,  159,
      158,  157,  152,  129,  124,  123,  122,  121,  120,  119,
      113,  112,  111,  103,   64,   59,   40,   65,   64,   40,
       59,   40,   49,   40,   40,  358,    3,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358
    } ;

static const flex_int16_t yy_chk[959] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    9,   15,   15,    9,    2,    9,    9,   16,
       16,   18,   18,   84,   21,   16,    9,   21,   84,    9,

        9,   19,   19,   19,   30,   30,   31,   31,   37,   37,
       38,   38,   39,   39,   19,   19,   45,   45,  366,   19,
       46,   46,   46,   19,  336,   19,    9,   19,   47,   47,
       48,   48,   48,   49,   49,   50,   50,  335,    2,    2,
       61,   61,   64,    2,   74,   51,   51,   51,   74,   31,
       37,  102,   30,  102,   30,   39,   60,   60,   38,   51,
       38,  324,   39,   52,   52,   52,   54,   54,   54,  323,
       38,   43,   43,   43,   43,   43,   43,   66,   66,   43,
       43,   61,  128,   43,   43,   43,  128,   43,   43,   54,
       64,   43,   43,   52,   53,   53,   53,   55,   55,   55,

      102,   56,   56,   56,   62,   62,   67,   67,   68,   68,
       53,   60,   69,   69,   55,   56,   53,  143,  143,   56,
       66,   70,   55,   70,  165,   75,  322,   75,   82,   56,
       75,  320,   70,  319,   82,   87,   87,   87,  165,   82,
       82,   89,   89,   89,  313,   62,   62,   67,  106,  106,
       87,  312,   69,  158,   62,   87,  158,   95,   95,   95,
       68,   85,   85,   89,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,  146,  146,   85,   95,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   88,   88,   88,
       90,   90,   90,   91,   91,   91,   92,   92,   92,  106,

       93,   93,   93,  311,   94,   94,   94,   96,   96,   96,
       85,   88,   85,   85,   93,   85,   94,   90,  310,   92,
       91,  307,   96,   97,   97,   98,   98,   99,   99,  100,
      100,  101,  101,  104,  104,  105,  105,  107,  107,   85,
       85,   85,  116,  306,  116,  132,  132,  132,  116,  133,
      133,  133,  134,  134,  134,  132,  305,  135,  135,  135,
      136,  136,  136,  133,  151,   97,  137,  137,  137,   99,
      304,   98,  101,  101,  136,  134,  150,  105,  150,  104,
      135,  105,  100,  144,  144,  107,  138,  138,  138,  303,
      137,  139,  139,  139,  140,  140,  140,  141,  141,  141,

      142,  142,  142,  139,  145,  145,  147,  147,  138,  148,
      148,  141,  151,  153,  153,  142,  302,  140,  154,  154,
      155,  155,  156,  156,  293,  150,  144,  183,  183,  183,
      184,  184,  184,  185,  185,  185,  188,  188,  188,  186,
      186,  186,  187,  187,  187,  292,  188,  145,  147,  189,
      189,  189,  190,  190,  190,  183,  289,  184,  185,  194,
      194,  154,  148,  153,  186,  195,  195,  187,  196,  196,
      190,  191,  191,  191,  155,  192,  192,  192,  288,  156,
      189,  193,  193,  193,  197,  197,  199,  199,  200,  200,
      201,  201,  287,  191,  202,  202,  284,  192,  283,  193,

      229,  229,  229,  230,  230,  230,  231,  231,  231,  240,
      240,  196,  232,  232,  232,  242,  242,  230,  243,  243,
      229,  233,  233,  233,  244,  244,  232,  282,  199,  234,
      234,  234,  281,  231,  280,  202,  235,  235,  235,  236,
      236,  236,  233,  237,  237,  237,  201,  238,  238,  238,
      239,  239,  239,  279,  234,  278,  237,  266,  266,  266,
      275,  275,  236,  267,  267,  267,  244,  268,  268,  268,
      277,  269,  269,  269,  238,  276,  270,  270,  270,  265,
      239,  271,  271,  271,  266,  269,  270,  272,  272,  272,
      273,  273,  273,  294,  294,  294,  264,  272,  262,  267,

      295,  295,  295,  268,  273,  296,  296,  296,  259,  271,
      295,  297,  297,  297,  258,  257,  294,  256,  296,  298,
      298,  298,  299,  299,  299,  300,  300,  300,  314,  314,
      314,  297,  315,  315,  315,  316,  316,  316,  317,  317,
      317,  318,  318,  318,  255,  298,  254,  299,  253,  252,
      314,  300,  315,  316,  329,  329,  329,  251,  317,  330,
      330,  330,  250,  331,  331,  331,  332,  332,  332,  338,
      338,  338,  318,  331,  339,  339,  339,  248,  247,  330,
      332,  246,  245,  338,  340,  340,  340,  341,  341,  341,
      329,  344,  344,  344,  345,  345,  345,  241,  346,  346,

      346,  347,  347,  347,  348,  348,  348,  341,  228,  227,
      339,  340,  346,  226,  348,  225,  344,  349,  349,  349,
      350,  350,  350,  345,  224,  223,  347,  351,  351,  351,
      352,  352,  352,  353,  353,  353,  354,  354,  354,  221,
      349,  220,  219,  353,  218,  350,  217,  354,  352,  355,
      355,  355,  351,  356,  356,  356,  357,  357,  357,  215,
      214,  213,  212,  211,  208,  206,  205,  356,  204,  355,
      203,  198,  182,  181,  180,  179,  178,  177,  176,  175,
      174,  173,  357,  359,  172,  359,  359,  359,  360,  171,
      360,  360,  360,  361,  361,  361,  362,  362,  362,  363,

      363,  364,  364,  364,  364,  364,  365,  170,  365,  365,
      365,  367,  169,  367,  367,  367,  368,  368,  368,  368,
      368,  168,  167,  166,  164,  163,  161,  160,  157,  152,
      149,  131,  130,  129,  127,  126,  125,  124,  123,  122,
      121,  120,  118,  117,  115,  114,  113,  112,  111,  110,
      109,  108,  103,   83,   81,   80,   79,   78,   77,   76,
       73,   72,   71,   65,   63,   58,   57,   36,   35,   33,
       29,   26,   20,    7,    6,    3,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,

      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "mf.lex"
#line 2 "mf.lex"
#include "mf.tab.h"
#line 775 "lex.yy.c"
#line 776 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 8 "mf.lex"


#line 999 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 359 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 877 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 10 "mf.lex"
{return INCLUDE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 11 "mf.lex"
{return EXPORT;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 13 "mf.lex"
{return DEFINE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 14 "mf.lex"
{return ENDEF;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 16 "mf.lex"
{return DEFINELINE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 18 "mf.lex"
{return IFDEF;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 19 "mf.lex"
{return IFNDEF;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 20 "mf.lex"
{return IFEQ;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 21 "mf.lex"
{return IFNEQ;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 22 "mf.lex"
{return ELSE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 23 "mf.lex"
{return ENDIF;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 25 "mf.lex"
{return COMMENT;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 27 "mf.lex"
{return TEMPLATE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 30 "mf.lex"
{return COMMAND;}
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 31 "mf.lex"
{return COMMAND;}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 33 "mf.lex"
{return SHELL_COMMAND;}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 34 "mf.lex"
{return SHELL_COMMAND;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 36 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 37 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 38 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 39 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 40 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 41 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 42 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 43 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 44 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 45 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 46 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 47 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 48 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 49 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 50 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 51 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 52 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 53 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 54 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 55 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 56 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 57 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 58 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 59 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 60 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 61 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 62 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 63 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 64 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 65 "mf.lex"
{return FUNCTION;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 67 "mf.lex"
{ return '('; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 68 "mf.lex"
{ return ')'; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 69 "mf.lex"
{ return '{'; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 70 "mf.lex"
{ return '$'; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 71 "mf.lex"
{ return ']'; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 72 "mf.lex"
{ return '['; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 73 "mf.lex"
{ return '-'; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 74 "mf.lex"
{ return '+'; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 75 "mf.lex"
{ return '"'; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 76 "mf.lex"
{ return '|'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 77 "mf.lex"
{ return ';'; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 78 "mf.lex"
{ return '/'; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 79 "mf.lex"
{ return '&'; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 80 "mf.lex"
{ return '<'; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 81 "mf.lex"
{ return '}'; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 82 "mf.lex"
{ return ','; }           
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 83 "mf.lex"
{ return '?'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 84 "mf.lex"
{ return '!'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 85 "mf.lex"
{ return ':'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 86 "mf.lex"
{ return '>'; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 87 "mf.lex"
{ return '`'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 88 "mf.lex"
{ return '\''; }
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 90 "mf.lex"
{ return EOL;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 91 "mf.lex"
{ static int once = 0; return once++ ? 0 : EOL;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 93 "mf.lex"
{return VAR_DEF;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 94 "mf.lex"
{return VAR_AUT;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 96 "mf.lex"
{ return SPECIAL; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 98 "mf.lex"
{yylval.str = strdup(yytext); return NAME;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 99 "mf.lex"
{yylval.str = strdup(yytext); return FILE_NAME;}  
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 100 "mf.lex"
{yylval.str = strdup(yytext); return PATH;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 103 "mf.lex"
ECHO;
	YY_BREAK
#line 1450 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 359 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 359 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 358);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 103 "mf.lex"



int yywrap()
{
	return 1;
}

